# Do not change version. This is the version of aws buildspec, not the version of your buildspec file.
version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing ...
      - npm install
  build:
    commands:
      - echo Building ...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
